version: '3'
services:
  ganache:
    container_name: ganache
    # https://hub.docker.com/r/trufflesuite/ganache-cli/
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    command: [
      "-d",
      "--db","/data/ganache",
      "--chainId","421612",
      "--blockTime","10"
    ]
    volumes:
      - ganache-data:/data/ganache
volumes:
  ganache-data: