version: '3'
services:
  ipfs:
    # Cannot run latest release v0.12.2 on Mac M1 due to this issue:
    # https://github.com/ipfs/go-ipfs/issues/8878.  Once v0.13 is released,
    # upgreade.
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - 4001:4001/tcp
      - 4001:4001/udp
      - 5001:5001
      - 8080:8080
      #- 8081:8081
    volumes:
      - ipfs-data:/data/ipfs
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taterdao-graph-node
    volumes:
      - postgres-data:/var/lib/postgresql/data
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    command: "-d --db /data/ganache --chainId 421612 --blockTime 5"
    volumes:
      - ganache-data:/data/ganache
  graph-node:
    image: graphprotocol/graph-node:latest
    ports:
      - 8000:8000/tcp # GraphiQL Interface
      - 8001:8001/tcp
      - 8020:8020/tcp
      - 8030:8030/tcp
    links:
      - "postgres:db"
      - "ganache:chain"
    environment:
      - postgres_host=db
      - postgres_user=user
      - postgres_pass=password
      - postgres_db=taterdao-graph-node
      - ipfs=http://ipfs:5001
      - ethereum=localhost:http://chain:8545
volumes:
  ipfs-data:
  postgres-data:
  ganache-data: