name: Deploy Autotasks
on:
  workflow_dispatch:
  # Triggered on push to any branch in order to test that no autotask
  # builds have been broken.
  push:
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/defender
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          # Autotask lambdas are run in Node v12 runtime.
          node-version: 12

      - name: "Install Dependencies"
        run: "yarn install --frozen-lockfile --dev"

      - name: Build
        run: |
          yarn autotask:build:index-contract-arbitrum-scheduled
          yarn autotask:build:index-contract-arbitrum-testnet-scheduled

      - name: Deploy (on push to Main)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "To do"
