name: Index Contract
on:
  workflow_dispatch:
  schedule:
    #- cron: "*/2 * * * *" # every 2 minutes
    - cron: "*/5 * * * *" # shortest interval provided by GHA is 5m
jobs:
  testnet:
    uses: ./.github/workflows/index.yml
    with:
      network_id: arbitrum_testnet
      network_endpoint: https://arb-rinkeby.g.alchemy.com/v2/znoYLBRcZ0b7eQd__jZQ6XIP5HuRK3Ge
    secrets:
      ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
      ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
  mainnet:
    uses: ./.github/workflows/index.yml
    with:
      network_id: arbitrum_mainnet
      network_endpoint: https://arb-mainnet.g.alchemy.com/v2/9M3hKpAbh5NStcX39OiZHIzYSr8iOgwW
    secrets:
      ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
      ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
 