# Reusable workflow
name: Index Contract
on:
  workflow_call:
    inputs:
      network_id:
        required: true
        type: string
      network_endpoint:
        required: true
        type: string
env:
  ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
  ALGOLIA_SEARCH_KEY: ${{ secrets.ALGOLIA_SEARCH_KEY }}
jobs:
  index:
    name: Index
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/indexing
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@master
      
      - name: "Install Node"
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: "Cache Dependencies"
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      
      - name: "Install JS Dependencies"
        run: "yarn install --frozen-lockfile --dev"

      - name: "Build"
        run: "yarn build"

      - name: "Index Script"
        run: "yarn index ${{ inputs.network_id}} ${{ inputs.network_endpoint }}"