name: Index Contract
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "*/2 * * * *" # every 2 minutes
jobs:
  testnet:
    uses: ./.github/workflows/index.yml
    with:
      network_id: arbitrum_testnet
      network_endpoint: https://arb-rinkeby.g.alchemy.com/v2/znoYLBRcZ0b7eQd__jZQ6XIP5HuRK3Ge
  # mainnet:
  #   uses: ./index.yml
  #   with:
  #     network_id: arbitrum-mainnet
  #     network_endpoint: https://arb-mainnet.g.alchemy.com/v2/9M3hKpAbh5NStcX39OiZHIzYSr8iOgwW
 