name: Index Contract
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "*/2 * * * *" # every 2 minutes
jobs:
  index-rinkeby:
    name: "Rinkeby"
    runs-on: ubuntu-latest
    if: false # Once re-deployed to Arbitrum
    defaults:
      run:
        working-directory: ./packages/indexing
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@master
      
      - name: "Install Node"
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: "Cache Dependencies"
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      
      - name: "Install JS Dependencies"
        run: "yarn install --frozen-lockfile --dev"

      - name: "Build"
        run: "yarn build"

      # - name: "Index"
      #   run: yarn build:addresses && node scripts/indexContract.js rinkeby https://eth-rinkeby.alchemyapi.io/v2/LB4UIgVJob-7MZeVcgMCLJ2GJn-2QZSe
      #   env:
      #     ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
      #     ALGOLIA_SEARCH_KEY: ${{ secrets.ALGOLIA_SEARCH_KEY }}

  index-mainnet:
    name: "Mainnet"
    runs-on: ubuntu-latest
    if: false # disable until deployed to mainnet
    defaults:
      run:
        working-directory: ./packages/indexing
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@master
      
      - name: "Install Node"
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: "Cache Dependencies"
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      
      - name: "Install JS Dependencies"
        run: "yarn install --frozen-lockfile --dev"

      - name: "Build"
        run: "yarn build"

      # - name: "Index"
      #   run: yarn build:addresses && node scripts/indexContract.js mainnet 
      #   env:
      #     ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
      #     ALGOLIA_SEARCH_KEY: ${{ secrets.ALGOLIA_SEARCH_KEY }}