name: tests-contracts
on:
  workflow_dispatch:
  push:
    paths:
      - "packages/contracts/**"
      - ".github/workflows/tests-contracts.yml"
jobs:
  tests:
    name: "Contract:Tests"
    runs-on: ubuntu-latest
    needs: []
    defaults:
      run:
        working-directory: ./packages/contracts
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@master
      - name: "Install Node"
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: "Cache Dependencies"
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: "Install JS Dependencies"
        run: "yarn install --frozen-lockfile --dev"
      - name: "Run tests"
        run: "yarn test"
        env:
          REPORT_GAS: false
  migrations:
    name: "Contract:Migrations"
    runs-on: ubuntu-latest
    needs: []
    defaults:
      run:
        working-directory: ./packages/contracts
    outputs:
      session-endpoint: ${{ steps.migration-00.outputs.session-endpoint }}
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@master

      - name: "Install Node"
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: "Cache Dependencies"
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: "Install JS Dependencies"
        run: "yarn install --frozen-lockfile --dev"

      - name: "Compile contracts"
        run: "yarn compile"

      - name: "Run Migration:00"
        id: migration-00
        uses: 721labs/hardhat-session-action@main
        with:
          cmd: "migration:00"
          hardhat-directory: ./packages/contracts

      - name: "Run Migration:01"
        uses: 721labs/hardhat-session-action@main
        with:
          cmd: "migration:01 --ci"
          session-id: ${{ steps.migration-00.outputs.session-id }}
          hardhat-directory: ./packages/contracts

      - name: "Run Migration:02"
        uses: 721labs/hardhat-session-action@main
        with:
          # Any writer address suffices
          cmd: "migration:02 --writer 0x7351dc227bacc5b33d1e14c778e46439852673b7"
          session-id: ${{ steps.migration-00.outputs.session-id }}
          hardhat-directory: ./packages/contracts

      - name: "Cache CI data"
        uses: actions/cache@v2
        with:
          path: |
            ./.ci/proxyInstanceAddress
          key: "ci-cache"
