name: tests-web
on:
  workflow_dispatch:
  push:
    paths:
      - "packages/web/**"
      - ".github/workflows/tests-web.yml"
jobs:
  e2e:
    name: "Web:Tests:E2E"
    runs-on: ubuntu-latest
    needs: []
    if: False
    defaults:
      run:
        working-directory: ./packages/web
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          working-directory: ./packages/web
  unit:
    name: "Web:Tests:Unit"
    runs-on: ubuntu-latest
    #needs: [contract-migrations]
    needs: []
    defaults:
      run:
        working-directory: ./packages/web
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Install Node"
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: "Cache Dependencies"
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: "Install Web Dependencies"
        run: "yarn install --frozen-lockfile --dev"

      - name: "Restore CI cache"
        uses: actions/cache@v2
        with:
          path: |
            ./.ci/proxyInstanceAddress
          key: "ci-cache"

      - name: "Run tests"
        run: "yarn test:unit"
        #env:
        #  CHAIN_ENDPOINT: ${{ needs.contract-migrations.outputs.session-endpoint }}
