name: Tests
on:
  workflow_dispatch:
  push:
jobs:
  contract-tests:
    name: "Contract:Tests"
    runs-on: ubuntu-latest
    needs: []
    defaults:
      run:
        working-directory: ./packages/contracts
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@master
      - name: "Install Node"
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: "Cache Dependencies"
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: "Install JS Dependencies"
        run: "yarn install --frozen-lockfile --dev"
      - name: "Run tests"
        run: "yarn test"
        env:
          REPORT_GAS: false
  contract-migrations:
    name: "Contract:Migrations"
    runs-on: ubuntu-latest
    needs: []
    defaults:
      run:
        working-directory: ./packages/contracts
    outputs:
      session-endpoint: ${{ steps.migration-00.outputs.session-endpoint }}
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@master
      
      - name: "Install Node"
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: "Cache Dependencies"
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      
      - name: "Install JS Dependencies"
        run: "yarn install --frozen-lockfile --dev"
      
      - name: "Compile contracts"
        run: "yarn compile"
      
      - name: "Run Migration:00"
        id: migration-00
        uses: 721labs/hardhat-session-action@main
        with:
          cmd: "migration:00 --write"
          hardhat-directory: ./packages/contracts
      
      # - name: "Run Migration:01"
      #   uses: 721labs/hardhat-session-action@main
      #   with:
      #     cmd: "migration:01 --write --address ''"
      #     session-id: ${{ steps.migration-00.outputs.session-id }}
      #     hardhat-directory: ./packages/contracts

      - name: "Cache CI data"
        uses: actions/cache@v2
        with:
          path: |
            ./.ci/proxyInstanceAddress
          key: "ci-cache"

  web-tests-e2e:
    name: "Web:Tests:E2E"
    runs-on: ubuntu-latest
    needs: []
    defaults:
      run:
        working-directory: ./packages/web
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          working-directory: ./packages/web
  web-tests-unit:
    name: "Web:Tests:Unit"
    runs-on: ubuntu-latest
    needs: [contract-migrations]
    defaults:
      run:
        working-directory: ./packages/web
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: "Install Node"
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      
      - name: "Cache Dependencies"
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      
      - name: "Install Web Dependencies"
        run: "yarn install --frozen-lockfile --dev"

      - name: "Restore CI cache"
        uses: actions/cache@v2
        with:
          path: |
            ./.ci/proxyInstanceAddress
          key: "ci-cache"

      - name: "Run tests"
        run: 'yarn test:unit'
        env:
          CHAIN_ENDPOINT: ${{ needs.contract-migrations.outputs.session-endpoint }}

